### ISSUE TITLE
Regarding the specification of argument type of deepCompare function

### ISSUE THREAD

**Issue by ishidad2** [symbol-blockchain-community/symbol-sdk-php#2]
# deepCompare関数の引数の型の指定について

以下のようなコードで署名の検証を行ってみたところエラーが発生しました。

```php
$aliceKey = new KeyPair(new PrivateKey('85B1B06DD5EE2A611325287705FA909442969B3C7FF47672B1EC34E9C41*****'));
/**
 * 署名
 */
$payload = "Hellow Symbol!";
$signature = $aliceKey->sign($payload);
echo "\n===署名===" . PHP_EOL;
echo $signature . PHP_EOL;

/**
 * 検証
 */
echo "\n===検証===" . PHP_EOL;
$v = new Verifier($aliceKey->publicKey());
$isVerified = $v->verify($payload, $signature);
echo "alice verified: " . PHP_EOL;
var_dump($isVerified);
```

エラー内容

```
Fatal error: Uncaught TypeError: SymbolSdk\Utils\ArrayHelpers::deepCompare(): Argument #1 ($lhs) must be of type array|int, string given, called in /work/vendor/symbol-blockchain-community/symbol-sdk/src/Symbol/Verifier.php on line 25 and defined in /work/vendor/symbol-blockchain-community/symbol-sdk/src/Utils/ArrayHelpers.php:19
Stack trace:
#0 /work/vendor/symbol-blockchain-community/symbol-sdk/src/Symbol/Verifier.php(25): SymbolSdk\Utils\ArrayHelpers::deepCompare('\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...', '%\x18\x915\xBF#\x07\xDC\xBC\xD1ez4\xAB\xC3...')
#1 /work/03_account.php(114): SymbolSdk\Symbol\Verifier->__construct(Object(SymbolSdk\CryptoTypes\PublicKey))
#2 {main}
```
エラー内容を参考に調べたところ、以下のArrayHelpersでarray|int型の引数を期待しているが、呼び出し元のVerifierでは文字列型が渡されていることが原因でエラーが発生しているようです。

https://github.com/symbol-blockchain-community/symbol-sdk-php/blob/main/src/Utils/ArrayHelpers.php#L19

```diff
- public static function deepCompare(array|int $lhs, array|int $rhs): int
+ public static function deepCompare(array|int|string $lhs, array|int|string $rhs): int
```

上記のようにstring型も許可したらエラーなく動きましたが、この実装が他に影響を及ぼさないかどうかはわかりません。

**Comment by ishidad2** [comment]
あと、`Verifier.php`で`SymbolSdk\CryptoTypes\PublicKey`クラスをuseしてあると良いかもです🙏（VSCodeで補完時にワーニングが表示されるので）

```diff
<?php

namespace SymbolSdk\Symbol;

use SymbolSdk\Impl\Ed25519;
use SymbolSdk\CryptoTypes\Signature;
use SymbolSdk\Utils\ArrayHelpers;
use Error;
+ use SymbolSdk\CryptoTypes\PublicKey;
```

**Comment by 0x070696E65** [comment]
> 上記のようにstring型も許可したらエラーなく動きましたが、この実装が他に影響を及ぼさないかどうかはわかりません

ありがとうございます！この修正で他に影響はありません。公開鍵の値を00埋めした場合でも正しく例外を投げるのを確認できました！

> SymbolSdk\CryptoTypes\PublicKeyクラスをuse

ついでに引数の型をPublicKey指定にしておきました🙏
